apiVersion: v1
kind: Service
metadata:
  name: transpipe-api-service
  namespace: transpipe
  labels:
    app: transpipe-api
spec:
  selector:
    app: transpipe-api
  ports:
    - port: 80
      targetPort: 5070
      protocol: TCP
  type: LoadBalancer
